# Generated by Django 5.2.3 on 2025-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achilometre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.CharField(choices=[('work', 'Travail'), ('personal', 'Personnel'), ('urgent', 'Urgent'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
